### ISSUE TITLE
修改建议：为“版权声明”添加背景，以区分正文

### ISSUE THREAD

**Issue by yansheng836** [JoeyBling/hexo-theme-yilia-plus#10]
## Feature Request
为“版权声明”添加样式,，可参考这个样式：

`yilia/source/main.0cf68a.css` 添加如下代码:
```css
.declare {
  background-color: #eaeaea;
  margin-top: 2em;
  border-left: 3px solid #ff1700;
  padding: .5em 1em; }
```
效果图参考：

![效果图](https://user-images.githubusercontent.com/45334066/63212774-deff1100-c13b-11e9-8ab4-4080c1f4e1a0.png)
