### ISSUE TITLE
Gitee 显示Error: 404 Project Not Found

### ISSUE THREAD

**Issue by Metatronxl** [JoeyBling/hexo-theme-yilia-plus#26]
## ❓问题

我的gitee配置好了之后在上方显示`Error: 404 Project Not Found`,请问是不是有什么地方配置除了问题？登录是可以登陆的，但是无法评论，点击Issue Page 是显示Github 的Page not found

## 🤔结果 & 预期

Please describe what you expected to see.(请描述一下你希望看到什么)

## 🐥环境 & 设置

**Node.js & npm version**

```bash
```

**Your site `_config.yml`** (Optional)

```yml
```

**Your theme `_config.yml`** (Optional)

```yml
```

**Your browsers** (Optional)

> The browser you use

**Your OSes** (Optional)

> what platforms (operating systems and devices) are affected?

**Comment by JoeyBling** [comment]
Gitee账号也需要创建对应`repo`配置的评论仓库,使用和配置跟Gitment差不多
> 参考[Hexo博客集成码云评论系统](https://www.jianshu.com/p/f5c4633524c7)

**Comment by Metatronxl** [comment]
![截屏2019-10-15下午3.12.33](https://tva1.sinaimg.cn/large/006y8mN6ly1g7ywn7sho1j31jk0ewgre.jpg)
是有在gitee上建立一个名叫‘blog’的仓库的

```
giteement:
  enable: true  # 是否启用码云评论系统
  # 是否使用官方js(false可以提升访问速度)
  remote: false
  redirect_uri: 'https://metatronxl.github.io/'   # 应用回调地址(请和配置的第三方应用保持一致)
  # 不能更改(网上开源项目`https://github.com/Rob--W/cors-anywhere`作者提供的专门用来跨域服务器的配置)
  oauth_uri: https://cors-anywhere.herokuapp.com/https://gitee.com/oauth/token
  giteeID: 'Metatronxl'  # 你的码云账号英文名
  # 存储评论的 repo name(需要在码云仓库创建公开仓库)
  repo: 'blog'
  gitment_oauth:
    client_id: 'xxx           #这里我打码一下
    client_secret: 'xxx'       #这里我打码一下
```
