### ISSUE TITLE
请问主页的名字怎样设置

### ISSUE THREAD

**Issue by Ottaliam** [JoeyBling/hexo-theme-yilia-plus#58]
## 🐥环境 & 设置

**Your site `_config.yml`** 

```yml
# Site
title: 森罗万象
subtitle: 'A somber reverie'
description: ''
#keywords:
author: Nazlim
#language: zh
#timezone: ''

```

**Your theme `_config.yml`**

```yml

```

## ❓问题
已经设置了author和subtitle，但是首页头像下方依然一片空白
[![d5p9lq.png](https://s1.ax1x.com/2020/08/27/d5p9lq.png)](https://imgchr.com/i/d5p9lq)
请问是需要配置别的地方吗
顺便，请问鼠标移到头像上头像会转一圈这个效果可以关闭吗
